name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install --legacy-peer-deps=true

      - name: Build project
        run: npm run build
        env:
          VITE_BLIZZ_USERNAME: ${{ secrets.VITE_BLIZZ_USERNAME }}
          VITE_BLIZZ_PASSWORD: ${{ secrets.VITE_BLIZZ_PASSWORD }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4.3.4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
